cursor            #ffb0cd
cursor_text_color #531d36

foreground            #eedfe2
background            #130c0f
selection_foreground  #412932
selection_background  #e1bdc9
url_color             #e1bdc9

#: black 000000 767676
color0  #191114
color8  #3c3235
#: red cc0403 f2201f
color1  #d03361
color9  #edafc1
#: green 19cb00 23fd00
color2  #e1bdc9
color10 #ffd9e4
#: yellow cecb00 fffd00
color3  #f1bc96
color11 #ffdcc4
#: blue 0d73cc 1a8fff
color4  #6e334d
color12 #ffb0cd
#: magenta cb1ed1 fd28ff
color5  #5a3f49
color13 #e1bdc9
#: cyan 0dcdcd 14ffff
color6  #633e22
color14 #f1bc96
#: white dddddd ffffff
color7  #d5c2c7
color15 #eedfe2

mark1_foreground #390721
mark1_background #ffd9e4
mark2_foreground #2a151e
mark2_background #ffd9e4
mark3_foreground #2f1400
mark3_background #ffdcc4

active_tab_foreground #531d36
active_tab_background #ffb0cd
inactive_tab_foreground #ffd9e4
inactive_tab_background #6e334d

active_border_color #ffb0cd
inactive_border_color #531d36
# bell_border_color #ff5a00
