# source = colors.conf

# wallpaper {
#     monitor =
#     # path    = $image
#     # path    = ~/Pictures/wallpaper/anime/astronaut2.png
#     fit_mode = cover
# }
# splash = false #to hide the random text on bottom
