cursor            #80d4d6
cursor_text_color #003738

foreground            #dde4e3
background            #090f0f
selection_foreground  #1b3435
selection_background  #b0cccc
url_color             #b0cccc

#: black 000000 767676
color0  #0e1415
color8  #2f3636
#: red cc0403 f2201f
color1  #26615c
color9  #5fc1b8
#: green 19cb00 23fd00
color2  #b0cccc
color10 #cce8e8
#: yellow cecb00 fffd00
color3  #b4c8e9
color11 #d4e3ff
#: blue 0d73cc 1a8fff
color4  #004f51
color12 #80d4d6
#: magenta cb1ed1 fd28ff
color5  #324b4c
color13 #b0cccc
#: cyan 0dcdcd 14ffff
color6  #354863
color14 #b4c8e9
#: white dddddd ffffff
color7  #bec8c8
color15 #dde4e3

mark1_foreground #002021
mark1_background #9cf1f3
mark2_foreground #041f20
mark2_background #cce8e8
mark3_foreground #061c36
mark3_background #d4e3ff

active_tab_foreground #003738
active_tab_background #80d4d6
inactive_tab_foreground #9cf1f3
inactive_tab_background #004f51

active_border_color #80d4d6
inactive_border_color #003738
# bell_border_color #ff5a00
